// ============================================================================
// Файл: opcode-table.ts
// Таблица диспетчеризации базовых опкодов
// Ключ - младшие 5 бит опкода (0x00..0x1f)
// ============================================================================

import type { OpcodeFn } from './uxn-types.js';
import {
    opAdd,
    opAnd,
    opBrk,
    opDei,
    opDeo,
    opDiv,
    opDup,
    opEqu,
    opEor,
    opGth,
    opInc,
    opJcn,
    opJmp,
    opJsr,
    opLda,
    opLdr,
    opLdz,
    opLth,
    opMul,
    opNeq,
    opNip,
    opOra,
    opOvr,
    opPop,
    opRot,
    opSft,
    opSta,
    opSth,
    opStr,
    opStz,
    opSub,
    opSwp,
} from './opcodes/index.js';

export const OPCODE_TABLE: Record<number, OpcodeFn> = {
    0x00: opBrk,
    0x01: opInc,
    0x02: opPop,
    0x03: opNip,
    0x04: opSwp,
    0x05: opRot,
    0x06: opDup,
    0x07: opOvr,
    0x08: opEqu,
    0x09: opNeq,
    0x0a: opGth,
    0x0b: opLth,
    0x0c: opJmp,
    0x0d: opJcn,
    0x0e: opJsr,
    0x0f: opSth,
    0x10: opLdz,
    0x11: opStz,
    0x12: opLdr,
    0x13: opStr,
    0x14: opLda,
    0x15: opSta,
    0x16: opDei,
    0x17: opDeo,
    0x18: opAdd,
    0x19: opSub,
    0x1a: opMul,
    0x1b: opDiv,
    0x1c: opAnd,
    0x1d: opOra,
    0x1e: opEor,
    0x1f: opSft,
};
